#pragma once

void test_METHOD_serializeRemote_WITH_remote_SHOULD_return_string(void);
void test_METHOD_serializeRemotes_WITH_two_remotes_SHOULD_return_string(void);
void test_METHOD_serializeRemotes_WITH_one_remote_SHOULD_return_string(void);
void test_METHOD_serializeNetworkConfig_WITH_config_SHOULD_return_string(void);
void test_METHOD_serializeSystemInfos_WITH_info_SHOULD_return_string(void);
void test_METHOD_serializeNetworks_WITH_one_network_SHOULD_return_string(void);
void test_METHOD_serializeNetworks_WITH_two_networks_SHOULD_return_string(void);